#!/bin/bash


# yes | sudo xbps-install -S mousepad geany ranger nnn wget picom

# Install fonts
# yes | sudo xbpx-install -S fonts-font-awesome fonts-ubuntu fonts-liberation2 fonts-liberation fonts-terminus

# EXA installation
# replace ls command in .bashrc file with line below
# alias ls='exa -al --long --header --color=always --group-directories-first' 
# sudo xbpx-install -S exa

# bpyton galculator youtube-dl-gui subleme geany flameshot okular peel google-chrome waterfox thunderbird
# audacity brasero handbrake k3b mvp vlc
# libreoffice pdfarranger Xornal++ redshift









printf "\e[1;32mDone! you can now reboot.\e[0m\n"
