#!/bin/bash

# XSessions and dwm.desktop
if [[ ! -d /usr/share/xsessions ]]; then
.loc    sudo mkdir /usr/share/xsessions
fi

cat > ./temp << "EOF"
[Desktop Entry]
Encoding=UTF-8
Name=dwm
Comment=Dynamic window manager
Exec=dwm
Icon=dwm
Type=XSession
EOF
sudo cp ./temp /usr/share/xsessions/dwm.desktop;rm ./temp

# Creating directories
mkdir ~/.config/suckless

# Creating .local/share/dwm
if [[ ! -d /.local/share/ ]]; then
    sudo mkdir /.local/share/dwm
fi

